@section('slider')
    @section('slider_search')
        @include('Mero::layout.slider_search')
    @show
    @section('slider_recent')
        @include('Mero::layout.slider_recent')
    @show
    @section('slider_comment')
        @include('Mero::layout.slider_comment')
    @show
@show