<?php

namespace Andruby\DeepDocs\Controllers;

use Andruby\DeepAdmin\Controllers\ContentController;
use SmallRuralDog\Admin\Form;
use SmallRuralDog\Admin\Grid;


class CatalogController extends ContentController
{
    protected function grid_list(Grid $grid)
    {
        $grid->addDialogForm($this->form()->isDialog());
        $grid->editDialogForm($this->form()->isDialog());
        return parent::grid_list($grid); // TODO: Change the autogenerated stub
    }

    protected function form_add(Form $form, $isEdit)
    {
        $form->isDialog();

        return $form; // TODO: Change the autogenerated stub
    }
}
